-- MySQL Script generated by MySQL Workbench
-- вт, 16-сер-2016 12:04:34 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema savelife
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema savelife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `savelife` DEFAULT CHARACTER SET utf8 COLLATE utf8_icelandic_ci ;
USE `savelife` ;

-- -----------------------------------------------------
-- Table `savelife`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `savelife`.`user_role` (
  `id` INT NOT NULL  ,
  `userRole` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `savelife`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `savelife`.`user` (
  `idUser` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `token` LONGTEXT ,
  `currentLatitude` DOUBLE ,
  `currentLongitude` DOUBLE ,
  `destinationLatitude` DOUBLE ,
  `destinationLongitude` DOUBLE ,
  `enable` BOOLEAN,
  `userRoleID` INT NOT NULL,
  PRIMARY KEY (`idUser`, `userRoleID`),
  INDEX `fk_user_user_role_idx` (`userRoleID` ASC),
  CONSTRAINT `fk_user_user_role`
    FOREIGN KEY (`userRoleID`)
    REFERENCES `savelife`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;